### ISSUE TITLE
dir error packages worspace

### ISSUE THREAD

**Issue by ma-blip** [slyfox1186/ffmpeg-build-script#31]
Tested on two independent machines.  

Packages and workspace are created in the the /ffmpeg-build-script folder but files are downloaded in / and unpacked in / creates a lot of mess.

On Ubuntu 22.04

Any idea why?

**Comment by rharmonson** [comment]
I can verify files are written to "/" on Debian 12 as well.

I do appreciate the recent update. It wasn't building for me at all a day or two prior to the recent commit. Thank you!

**Comment by rharmonson** [comment]
cleanup using `sudo ./build-ffmpeg.sh -c` does not work.

**Comment by slyfox1186** [comment]
This has been fixed in version 3.8.0.

I apologize for the inconvenience this may have caused you. The downloads directory was corrupt and I believe I have fixed it after testing things in Windows WSL and Native Ubuntu 24.04.

The cleanup command will definitely not work given where the downloads folder was pointed. It should work now that the script has been fixed.

**Comment by rharmonson** [comment]
Thank you!

I am using Debian 12 and will test and open issues as needed.
