### ISSUE TITLE
ninja build fails due to cmake missing

### ISSUE THREAD

**Issue by rharmonson** [slyfox1186/ffmpeg-build-script#32]
After a clean Debian 12 installation and installing git and build-essential, the build script fails at "Building ninja - version 1.12.1" due to cmake missing.  I installed the cmake package and was able to build ninja.

Question: I noted cmake is built five steps or so after ninja. Is it the intent to build cmake then ninja using the built cmake? Not my area of expertise so may be a dumb question.

Thank you for the amazing script!

**Comment by slyfox1186** [comment]
Yes.

Regarding your specific question about the events of ninja and cmake:
Step 1 - Build the latest release version of cmake available.
Step 2 - Build the latest release version of ninja with the latest version of cmake you just installed. This is due to how the PATH variable has been assigned. The higher directories take priority over lower directories. "$workspace/bin" in positioned very high up for this reason.

Some of these repositories are SO fresh that you need the latest cmake or you can run into issues with some of them when building and installing.

**Comment by rharmonson** [comment]
Understood and thank you for the explaination.

My first time using your script and building ffmpeg. I will go build it again and if I get stuck, I will open a new issue.

Hope you are recovered. Best wishes!
