### ISSUE TITLE
Does Not Run with Command Given

### ISSUE THREAD

**Issue by kpirnie** [slyfox1186/ffmpeg-build-script#35]
`bash build-ffmpeg.sh --build -compiler=clang -j 8 -l -n`
Simply displays the help

Ubuntu 24.04

**Comment by kpirnie** [comment]
![image](https://github.com/slyfox1186/ffmpeg-build-script/assets/48323656/8fa5eac7-fd1b-4e78-b5a9-ffa272fd4ce4)

**Comment by slyfox1186** [comment]
The issue is with the shift command at the end of the while loop that starts around line 565. It unconditionally shifts the arguments by 1 position in each iteration, regardless of whether an argument was consumed or not. This causes the script to incorrectly parse the arguments and eventually fall into the *) case, which displays the usage information and exits.

A new version of the script was just released to fix this issue.

If you have other problems let me know.

I will mark this as closed.
