### ISSUE TITLE
Any Plans to Support Ubuntu Derivatives Like Zorin or Mint?

### ISSUE THREAD

**Issue by bwanshoom** [slyfox1186/ffmpeg-build-script#37]
Zorin and Mint are both just Ubuntu under the hood - could you add support for them?

**Comment by slyfox1186** [comment]
I have updated the script. I do not have these distros to test readily available so you will need to help direct me on how to fix any errors if they occur.

I modified the get_os_version function to include these as if Ubuntu is being used instead so I am betting it will work.

However, keep me up to date and re-open this ticket if anything is not working correctly. 

Otherwise, look for my new release(s) today.
